#!/bin/sh
set -e
die() {
    echo "error: $@" >&2
    exit 1
}

[ -e ./README.md ]   \
    || die "you must run this script from the root of the repository"

# Copy the rust directory from bin/src/rust to bin/src/rust-1.73.0-patched
# and apply the patch.

# The patch is generated by running:
# diff -Naur --exclude=".git" bin/src/rust bin/src/rust-1.73.0-patched > patch/rust.diff

# Rename the rust directory to rust-1.73.0-patched
mv bin/src/rust bin/src/rust-1.73.0-patched
patch -p3 --directory=bin/src/rust-1.73.0-patched < patch/rust.diff