build:
	cd init && cargo build

build-release:
	cd init && cargo build --release
	
install:
	cd init && ./install.sh

fmt:
	cd iron && cargo fmt
	cd init && cargo fmt

clean:
	cd iron && cargo clean
	cd init && cargo clean

