build:
	cd init && cargo build

build-release:
	cd init && cargo build --release

install:
	cd init && ./install.sh

fmt:
	cd init && cargo fmt
	cd syscall && cargo fmt

clean:
	cd init && cargo clean
	cd syscall && cargo clean
