name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: ninja-build lld libssl-dev qemu-system-x86
        version: 1.0

    - name: Build kernel and userland
      run: make build

    - name: Virtualized integration tests
      run: make run-test
